---

dependencies: []

galaxy_info:

  author:              Elao
  company:             Elao
  description: >
    An oh-my-zsh role for elao symfony standard vagrant box
  license:             MIT
  min_ansible_version: 2.0.0
  platforms:
    - name: Debian
      versions:
        - wheezy
        - jessie
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - development
    - web
