---
- name: "OS X | package control | ensure package control permissions"
  file:
    state: directory
    path: "{{ item }}"
    mode: 0774
    owner: "{{ sublime_user }}"
    group: "{{ sublime_user_group }}"
  with_items:
    - "{{ __osx_pc_dir }}"
    - "{{ __osx_pc_user_dir }}"

- name: "OS X | package control | ensure 'Package Control.sublime-package' is present"
  get_url:
    url: "{{ __pc_url }}"
    dest: "{{ __osx_pc_dir }}/Package Control.sublime-package"
    mode: 0774
    owner: "{{ sublime_user }}"
    group: "{{ sublime_user_group }}"

- name: "OS X | package control | generate 'Package Control.sublime-settings'"
  template:
    src: ../templates/Package Control.sublime-settings.j2
    dest: "{{ __osx_pc_user_dir }}/Package Control.sublime-settings"
    mode: 0774
    owner: "{{ sublime_user }}"
    group: "{{ sublime_user_group }}"
