---
- name: write tokens spacer
  lineinfile:
    line: "\n# ---TOKENS--------------------------------------------------------------------"
    state: "{{ state }}"
    dest: "{{ dest }}"
    # insertafter: EOF
    create: true
  tags:
    - tokens

- name: write tokens
  lineinfile:
    line: "export {{item.key}}=\"{{item.value}}\""
    state: "{{ state }}"
    dest: "{{ dest }}"
    # insertafter: EOF
  with_dict: "{{ shell_config_tokens }}"
  tags:
    - tokens
