namespace: the_new_flesh
name: dev_roles
version: "1.0.0"
readme: "README.md"
authors:
    - "Alex Braun <alexander.g.braun@gmail.com>"
dependencies: []
license:
    - "MIT"
tags:
    - visual_effects
    - vfx
    - computer_vision
    - cv
    - machine_learning
    - artificial_intelligence
    - ai
    - developer
    - ubuntu
    - collection
repository: "https://www.github.com/theNewFlesh/dev-roles"