---
__source: "https://download.sublimetext.com"
__arch: "{% if ansible_architecture == 'x86_64' %}amd64{% else %}i386{% endif %}"

# debian
__url_deb: "{{ __source }}/sublime-text_build-{{ sublime_build }}_{{ __arch }}.deb"
__tmp_deb: "/tmp/{{ sublime_build }}sublimetext.deb"

# os x
__url_dmg: "{{ __source }}/Sublime%20Text%20Build%20{{ sublime_build }}.dmg"
__tmp_dmg: "/tmp/sublimetext-{{ sublime_build }}.dmg"
__mount: "/Volumes/Sublime Text/"
