---
dependencies: []

galaxy_info:
  author: theNewFlesh
  description: conky is a system resource HUD for linux desktops
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - development
    - system
