---
dependencies: []

galaxy_info:
  role_name: plank_config
  author: theNewFlesh
  description: Configure Plank dock application
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - development
    - system
