---
dependencies: []

galaxy_info:
  author: theNewFlesh
  description: install and configure unity-tweak-tool
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - development
    - system
