- name: "ensure {{ ansible_user_dir }}/.config/autostart exists"
  file:
    dest: "{{ ansible_user_dir }}/.config/autostart"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  tags:
    - config

- name: install autostart items
  template:
    src: ../templates/template.desktop.j2
    dest: "{{ ansible_user_dir }}/.config/autostart/{{ item.name }}.desktop"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items: "{{ autostart_items }}"
  tags:
    - config
