---
dependencies: []

galaxy_info:
  role_name: foundry_licensing_utility_config
  author: theNewFlesh
  description: Configures the Foundry Licensng Utility 
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - development
    - system
