- name: "Debian | ensure alessandro-strada PPA is {{ state }}."
  apt_repository:
    repo: ppa:alessandro-strada/ppa
    state: "{{ state }}"
  when: ansible_os_family == "Debian"
  tags:
    - install
    - debian

- name: "Debian | ensure google-drive-ocamlfuse is {{ state }}."
  apt:
    name: google-drive-ocamlfuse
    state: "{{ state }}"
  when: ansible_os_family == "Debian"
  tags:
    - install
    - debian
