---
dependencies: []

galaxy_info:
  role_name: linux_hotkeys
  author: theNewFlesh
  description: Configures linux hotkeys
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - development
    - system
