---
# permissions
konsole_user: "{{ ansible_user }}"
konsole_user_group: "{{ ansible_user }}"

# dev.profile
konsole_color_scheme_name: henanigans
konsole_font: Monaco
konsole_font_size: 11
konsole_cursor_color: 126,196,207
konsole_shell: /bin/bash
konsole_width: 100
konsole_height: 100

# dev.colorscheme
konsole_background: 36,36,36
konsole_background_intense: 36,36,36
konsole_color_0: 36,36,36
konsole_color_0_intense: 52,52,52
konsole_color_1: 222,149,142
konsole_color_1_intense: 247,126,112
konsole_color_2: 160,209,123
konsole_color_2_intense: 139,209,85
konsole_color_3: 233,234,190
konsole_color_3_intense: 232,234,126
konsole_color_4: 147,182,230
konsole_color_4_intense: 95,149,222
konsole_color_5: 172,146,222
konsole_color_5_intense: 201,143,222
konsole_color_6: 182,236,243
konsole_color_6_intense: 126,196,207
konsole_color_7: 235,180,131
konsole_color_7_intense: 235,158,88
konsole_foreground: 244,244,244
konsole_foreground_intense: 164,164,164
konsole_opacity: 0.8

# dev.shortcuts.rc
konsole_key_clear_history_and_reset: Meta+L
konsole_key_close_session: Ctrl+W
konsole_key_edit_copy: Ctrl+C
konsole_key_edit_find: Ctrl+F
konsole_key_edit_paste: Ctrl+V
konsole_key_new_tab: Ctrl+T
konsole_key_new_window: Ctrl+N
konsole_key_select_line: Ctrl+A
konsole_key_sigint_signal: Meta+C
konsole_key_sigkill_signal: Meta+Z
konsole_key_adjust_history: none
konsole_key_clear_history: none
konsole_key_copy_input_to: none
konsole_key_copy_input_to_all_tabs: none
konsole_key_copy_input_to_none: none
konsole_key_copy_input_to_selected_tabs: none
konsole_key_edit_current_profile: none
konsole_key_edit_find_next: none
konsole_key_edit_find_prev: none
konsole_key_enlarge_font: none
konsole_key_file_print: none
konsole_key_file_save_as: none
konsole_key_monitor_activity: none
konsole_key_monitor_silence: none
konsole_key_open_browser: none
konsole_key_paste_selection: none
konsole_key_rename_session: none
konsole_key_select_all: none
konsole_key_send_signal: none
konsole_key_set_encoding: none
konsole_key_shrink_font: none
konsole_key_sigcont_signal: none
konsole_key_sighup_signal: none
konsole_key_sigstop_signal: none
konsole_key_sigterm_signal: none
konsole_key_sigusr1_signal: none
konsole_key_sigusr2_signal: none
konsole_key_zmodem_upload: none
konsole_key_fullscreen: none
konsole_key_activate_menu: none
konsole_key_add_bookmark: none
konsole_key_add_bookmarks_list: none
konsole_key_clone_tab: none
konsole_key_close_window: none
konsole_key_detach_tab: none
konsole_key_detach_view: none
konsole_key_edit_bookmarks: none
konsole_key_expand_active_view: none
konsole_key_focus_view_above: none
konsole_key_focus_view_below: none
konsole_key_focus_view_left: none
konsole_key_focus_view_right: none
konsole_key_help_about_app: none
konsole_key_help_about_kde: none
konsole_key_help_contents: none
konsole_key_help_donate: none
konsole_key_help_report_bug: none
konsole_key_help_whats_this: none
konsole_key_last_tab: none
konsole_key_last_used_tab_reverse: none
konsole_key_last_used_tab: none
konsole_key_manage_profiles: none
konsole_key_maximize_current_terminal: none
konsole_key_move_tab_to_left: none
konsole_key_move_tab_to_right: none
konsole_key_next_tab: none
konsole_key_options_configure_keybinding: none
konsole_key_options_configure_notifications: none
konsole_key_options_configure: none
konsole_key_options_show_menubar: none
konsole_key_previous_tab: none
konsole_key_reset_font_size: none
konsole_key_shrink_active_view: none
konsole_key_split_view_left_right: none
konsole_key_split_view_top_bottom: none
konsole_key_switch_application_language: none
konsole_key_toggle_two_tabs: none
konsole_key_view_readonly: none
konsole_key_switch_to_tab_0: none
konsole_key_switch_to_tab_1: none
konsole_key_switch_to_tab_2: none
konsole_key_switch_to_tab_3: none
konsole_key_switch_to_tab_4: none
konsole_key_switch_to_tab_5: none
konsole_key_switch_to_tab_6: none
konsole_key_switch_to_tab_7: none
konsole_key_switch_to_tab_8: none
konsole_key_switch_to_tab_9: none
konsole_key_switch_to_tab_10: none
konsole_key_switch_to_tab_11: none
konsole_key_switch_to_tab_12: none
konsole_key_switch_to_tab_13: none
konsole_key_switch_to_tab_14: none
konsole_key_switch_to_tab_15: none
konsole_key_switch_to_tab_16: none
konsole_key_switch_to_tab_17: none
konsole_key_switch_to_tab_18: none

# konsolerc
konsole_show_app_name_on_titlebar: false
konsole_show_window_title_on_titlebar: true
konsole_tab_bar_position: Top
konsole_tab_bar_visibility: ShowTabBarWhenNeeded
konsole_menu_bar_enabled: true
konsole_show_menu_bar_by_default: true