---
- name: "Debian | configure sublime user hotkeys"
  template:
    src: ../templates/user.sublime-keymap.j2
    dest: "{{ ansible_user_dir }}/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap"
    mode: 0774
    owner: "{{ sublime_user }}"
    group: "{{ sublime_user_group }}"
