# xkb key bindings
linux_hotkeys_xkb_pc_rctl:                       ctrl-r
linux_hotkeys_xkb_pc_lctl:                       ctrl-l
linux_hotkeys_xkb_pc_rtsh:                       shift-r
linux_hotkeys_xkb_pc_lfsh:                       shift-l
linux_hotkeys_xkb_pc_lwin:                       super-l
linux_hotkeys_xkb_pc_rwin:                       super-r
linux_hotkeys_xkb_pc_supr:                       super-l
linux_hotkeys_xkb_pc_alt:                        alt-l
linux_hotkeys_xkb_pc_caps:                       caps
linux_hotkeys_xkb_pc_meta:                       meta-l
linux_hotkeys_xkb_pc_hypr:                       hyper-l

# gnome hotkeys
linux_hotkeys_area_screenshot:                   ctrl+super+1
linux_hotkeys_area_screenshot_clip:              ctrl+super+2
linux_hotkeys_battery_status:                    ctrl+super+3
linux_hotkeys_battery_status_static:             ctrl+super+4
linux_hotkeys_calculator:                        ctrl+super+5
linux_hotkeys_calculator_static:                 ctrl+super+6
linux_hotkeys_control_center:                    ctrl+super+7
linux_hotkeys_control_center_static:             ctrl+super+8
linux_hotkeys_decrease_text_size:                ctrl+super+9
linux_hotkeys_eject:                             ctrl+super+0
linux_hotkeys_eject_static:                      super+1
linux_hotkeys_email:                             super+2
linux_hotkeys_email_static:                      super+3
linux_hotkeys_help:                              super+4
linux_hotkeys_hibernate:                         super+5
linux_hotkeys_hibernate_static:                  super+6
linux_hotkeys_home:                              super+7
linux_hotkeys_home_static:                       super+8
linux_hotkeys_increase_text_size:                super+9
linux_hotkeys_keyboard_brightness_down:          super+0
linux_hotkeys_keyboard_brightness_down_static:   shift+super+1
linux_hotkeys_keyboard_brightness_toggle:        shift+super+2
linux_hotkeys_keyboard_brightness_toggle_static: shift+super+3
linux_hotkeys_keyboard_brightness_up:            shift+super+4
linux_hotkeys_keyboard_brightness_up_static:     shift+super+5
linux_hotkeys_logout:                            shift+super+6
linux_hotkeys_magnifier:                         shift+super+7
linux_hotkeys_magnifier_zoom_in:                 shift+super+8
linux_hotkeys_magnifier_zoom_out:                shift+super+9
linux_hotkeys_media:                             shift+super+0
linux_hotkeys_media_static:                      ctrl+shift+print
linux_hotkeys_mic_mute:                          shift+print
linux_hotkeys_mic_mute_static:                   xf86battery
linux_hotkeys_next:                              ""
linux_hotkeys_next_static:                       xf86calculator
linux_hotkeys_on_screen_keyboard:                ""
linux_hotkeys_pause:                             xf86tools
linux_hotkeys_pause_static:                      ""
linux_hotkeys_play:                              ""
linux_hotkeys_play_static:                       xf86eject
linux_hotkeys_playback_forward:                  ""
linux_hotkeys_playback_forward_static:           xf86mail
linux_hotkeys_playback_random:                   ""
linux_hotkeys_playback_random_static:            super+f1
linux_hotkeys_playback_repeat:                   xf86suspend
linux_hotkeys_playback_repeat_static:            ""
linux_hotkeys_playback_rewind:                   xf86explorer
linux_hotkeys_playback_rewind_static:            ""
linux_hotkeys_power:                             ""
linux_hotkeys_power_static:                      xf86kbdbrightnessdown
linux_hotkeys_previous:                          ""
linux_hotkeys_previous_static:                   xf86kbdlightonoff
linux_hotkeys_rfkill:                            ""
linux_hotkeys_rfkill_bluetooth:                  xf86kbdbrightnessup
linux_hotkeys_rfkill_bluetooth_static:           ""
linux_hotkeys_rfkill_static:                     control+alt+delete
linux_hotkeys_rotate_video_lock:                 alt+super+equal
linux_hotkeys_rotate_video_lock_static:          alt+super+minus
linux_hotkeys_screen_brightness_cycle:           alt+super+8
linux_hotkeys_screen_brightness_cycle_static:    xf86audiomedia
linux_hotkeys_screen_brightness_down:            ""
linux_hotkeys_screen_brightness_down_static:     xf86audiomicmute
linux_hotkeys_screen_brightness_up:              ""
linux_hotkeys_screen_brightness_up_static:       xf86audionext
linux_hotkeys_screencast:                        ""
linux_hotkeys_screenreader:                      ""
linux_hotkeys_screensaver:                       xf86audiopause
linux_hotkeys_screensaver_static:                ""
linux_hotkeys_screenshot:                        xf86audioplay
linux_hotkeys_screenshot_clip:                   ""
linux_hotkeys_search:                            xf86audioforward
linux_hotkeys_search_static:                     ""
linux_hotkeys_stop:                              xf86audiorandomplay
linux_hotkeys_stop_static:                       ""
linux_hotkeys_suspend:                           xf86audiorepeat
linux_hotkeys_suspend_static:                    ""
linux_hotkeys_terminal:                          xf86audiorewind
linux_hotkeys_toggle_contrast:                   ""
linux_hotkeys_touchpad_off:                      xf86poweroff
linux_hotkeys_touchpad_off_static:               ""
linux_hotkeys_touchpad_on:                       xf86audioprev
linux_hotkeys_touchpad_on_static:                ""
linux_hotkeys_touchpad_toggle:                   xf86bluetooth
linux_hotkeys_touchpad_toggle_static:            ""
linux_hotkeys_volume_down:                       xf86wlan
linux_hotkeys_volume_down_precise:               ""
linux_hotkeys_volume_down_precise_static:        super+o
linux_hotkeys_volume_down_quiet:                 ""
linux_hotkeys_volume_down_quiet_static:          xf86monbrightnesscycle
linux_hotkeys_volume_down_static:                ""
linux_hotkeys_volume_mute:                       xf86monbrightnessdown
linux_hotkeys_volume_mute_quiet:                 ""
linux_hotkeys_volume_mute_quiet_static:          xf86monbrightnessup
linux_hotkeys_volume_mute_static:                ""
linux_hotkeys_volume_up:                         ctrl+shift+alt+r
linux_hotkeys_volume_up_precise:                 alt+super+s
linux_hotkeys_volume_up_precise_static:          xf86screensaver
linux_hotkeys_volume_up_quiet:                   super+l
linux_hotkeys_volume_up_quiet_static:            ctrl+print
linux_hotkeys_volume_up_static:                  print
linux_hotkeys_window_screenshot:                 xf86search
linux_hotkeys_window_screenshot_clip:            ""
linux_hotkeys_www:                               super+q
linux_hotkeys_www_static:                        xf86audiostop
linux_hotkeys_app_ctrl_hotkey_1:                 ""
linux_hotkeys_app_ctrl_hotkey_10:                xf86sleep
linux_hotkeys_app_ctrl_hotkey_2:                 ""
linux_hotkeys_app_ctrl_hotkey_3:                 primary+alt+t
linux_hotkeys_app_ctrl_hotkey_4:                 ""
linux_hotkeys_app_ctrl_hotkey_5:                 xf86touchpadoff
linux_hotkeys_app_ctrl_hotkey_6:                 ""
linux_hotkeys_app_ctrl_hotkey_7:                 xf86touchpadon
linux_hotkeys_app_ctrl_hotkey_8:                 ""
linux_hotkeys_app_ctrl_hotkey_9:                 xf86touchpadtoggle
linux_hotkeys_app_hotkey_1:                      ""
linux_hotkeys_app_hotkey_10:                     shift+xf86audiolowervolume
linux_hotkeys_app_hotkey_2:                      ""
linux_hotkeys_app_hotkey_3:                      alt+xf86audiolowervolume
linux_hotkeys_app_hotkey_4:                      ""
linux_hotkeys_app_hotkey_5:                      xf86audiolowervolume
linux_hotkeys_app_hotkey_6:                      ""
linux_hotkeys_app_hotkey_7:                      alt+xf86audiomute
linux_hotkeys_app_hotkey_8:                      ""
linux_hotkeys_app_hotkey_9:                      xf86audiomute
linux_hotkeys_app_shift_hotkey_1:                ""
linux_hotkeys_app_shift_hotkey_10:               shift+xf86audioraisevolume
linux_hotkeys_app_shift_hotkey_2:                ""
linux_hotkeys_app_shift_hotkey_3:                alt+xf86audioraisevolume
linux_hotkeys_app_shift_hotkey_4:                ""
linux_hotkeys_app_shift_hotkey_5:                xf86audioraisevolume
linux_hotkeys_app_shift_hotkey_6:                ""
linux_hotkeys_app_shift_hotkey_7:                ctrl+alt+print
linux_hotkeys_app_shift_hotkey_8:                alt+print
linux_hotkeys_app_shift_hotkey_9:                xf86www
linux_hotkeys_shortcut:                          ""
linux_hotkeys_activate_window_menu:              alt+space
linux_hotkeys_begin_move:                        alt+f7
linux_hotkeys_begin_resize:                      alt+f8
linux_hotkeys_close:                             alt+f4
linux_hotkeys_cycle_group:                       alt+f6
linux_hotkeys_cycle_group_backward:              shift+alt+f6
linux_hotkeys_cycle_panels:                      control+alt+esc
linux_hotkeys_cycle_panels_backward:             shift+control+alt+esc
linux_hotkeys_cycle_windows:                     alt+esc
linux_hotkeys_cycle_windows_backward:            shift+alt+esc
linux_hotkeys_maximize:                          super+up
linux_hotkeys_minimize:                          super+h
linux_hotkeys_move_to_monitor_down:              super+shift+down
linux_hotkeys_move_to_monitor_left:              super+shift+left
linux_hotkeys_move_to_monitor_right:             super+shift+right
linux_hotkeys_move_to_monitor_up:                super+shift+up
linux_hotkeys_move_to_workspace_1:               super+shift+home
linux_hotkeys_move_to_workspace_down:            super+shift+page-down
linux_hotkeys_move_to_workspace_last:            super+shift+end
linux_hotkeys_move_to_workspace_left:            control+shift+alt+left
linux_hotkeys_move_to_workspace_right:           control+shift+alt+right
linux_hotkeys_move_to_workspace_up:              super+shift+page-up
linux_hotkeys_panel_main_menu:                   alt+f1
linux_hotkeys_panel_run_dialog:                  alt+f2
linux_hotkeys_show_desktop:                      primary+super+d
linux_hotkeys_switch_applications:               super+tab
linux_hotkeys_switch_applications_backward:      shift+super+tab
linux_hotkeys_switch_group:                      super+above-tab
linux_hotkeys_switch_group_backward:             shift+super+above-tab
linux_hotkeys_switch_input_source:               super+space
linux_hotkeys_switch_input_source_backward:      shift+super+space
linux_hotkeys_switch_panels:                     control+alt+tab
linux_hotkeys_switch_panels_backward:            shift+control+alt+tab
linux_hotkeys_switch_to_workspace_1:             super+home
linux_hotkeys_switch_to_workspace_down:          super+page-down
linux_hotkeys_switch_to_workspace_last:          super+end
linux_hotkeys_switch_to_workspace_left:          control+alt+left
linux_hotkeys_switch_to_workspace_right:         control+alt+right
linux_hotkeys_switch_to_workspace_up:            super+page-up
linux_hotkeys_switch_windows:                    alt+tab
linux_hotkeys_switch_windows_backward:           shift+alt+tab
linux_hotkeys_toggle_maximized:                  alt+f10
linux_hotkeys_unmaximize:                        super+down
linux_hotkeys_rotate_monitor:                    xf86rotatewindows
linux_hotkeys_switch_monitor:                    super+p
linux_hotkeys_toggle_tiled_left:                 super+left
linux_hotkeys_toggle_tiled_right:                super+right
linux_hotkeys_focus_active_notification:         super+n
linux_hotkeys_open_application_menu:             super+f10
linux_hotkeys_switch_to_application_1:           super+1
linux_hotkeys_switch_to_application_2:           super+2
linux_hotkeys_switch_to_application_3:           super+3
linux_hotkeys_switch_to_application_4:           super+4
linux_hotkeys_switch_to_application_5:           super+5
linux_hotkeys_switch_to_application_6:           super+6
linux_hotkeys_switch_to_application_7:           super+7
linux_hotkeys_switch_to_application_8:           super+8
linux_hotkeys_switch_to_application_9:           super+9
linux_hotkeys_toggle_application_view:           super+a
linux_hotkeys_toggle_message_tray:               super+v
linux_hotkeys_toggle_overview:                   super+s
linux_hotkeys_always_on_top:                     ""
linux_hotkeys_lower:                             ""
linux_hotkeys_maximize_horizontally:             ""
linux_hotkeys_maximize_vertically:               ""
linux_hotkeys_move_to_center:                    ""
linux_hotkeys_move_to_corner_ne:                 ""
linux_hotkeys_move_to_corner_nw:                 ""
linux_hotkeys_move_to_corner_se:                 ""
linux_hotkeys_move_to_corner_sw:                 ""
linux_hotkeys_move_to_side_e:                    ""
linux_hotkeys_move_to_side_n:                    ""
linux_hotkeys_move_to_side_s:                    ""
linux_hotkeys_move_to_side_w:                    ""
linux_hotkeys_move_to_workspace_10:              ""
linux_hotkeys_move_to_workspace_11:              ""
linux_hotkeys_move_to_workspace_12:              ""
linux_hotkeys_move_to_workspace_2:               ""
linux_hotkeys_move_to_workspace_3:               ""
linux_hotkeys_move_to_workspace_4:               ""
linux_hotkeys_move_to_workspace_5:               ""
linux_hotkeys_move_to_workspace_6:               ""
linux_hotkeys_move_to_workspace_7:               ""
linux_hotkeys_move_to_workspace_8:               ""
linux_hotkeys_move_to_workspace_9:               ""
linux_hotkeys_raise:                             ""
linux_hotkeys_raise_or_lower:                    ""
linux_hotkeys_set_spew_mark:                     ""
linux_hotkeys_switch_to_workspace_10:            ""
linux_hotkeys_switch_to_workspace_11:            ""
linux_hotkeys_switch_to_workspace_12:            ""
linux_hotkeys_switch_to_workspace_2:             ""
linux_hotkeys_switch_to_workspace_3:             ""
linux_hotkeys_switch_to_workspace_4:             ""
linux_hotkeys_switch_to_workspace_5:             ""
linux_hotkeys_switch_to_workspace_6:             ""
linux_hotkeys_switch_to_workspace_7:             ""
linux_hotkeys_switch_to_workspace_8:             ""
linux_hotkeys_switch_to_workspace_9:             ""
linux_hotkeys_toggle_above:                      ""
linux_hotkeys_toggle_fullscreen:                 ""
linux_hotkeys_toggle_on_all_workspaces:          ""
linux_hotkeys_toggle_shaded:                     ""
linux_hotkeys_tab_popup_cancel:                  ""
linux_hotkeys_tab_popup_select:                  ""

# gtile hotkeys
linux_hotkeys_gtile_action_change_tiling:        ""
linux_hotkeys_gtile_action_contract_bottom:      ""
linux_hotkeys_gtile_action_contract_left:        ""
linux_hotkeys_gtile_action_contract_right:       ""
linux_hotkeys_gtile_action_contract_top:         ""
linux_hotkeys_gtile_action_expand_bottom:        ""
linux_hotkeys_gtile_action_expand_left:          ""
linux_hotkeys_gtile_action_expand_right:         ""
linux_hotkeys_gtile_action_expand_top:           ""
linux_hotkeys_gtile_action_move_down:            ""
linux_hotkeys_gtile_action_move_left:            ""
linux_hotkeys_gtile_action_move_right:           ""
linux_hotkeys_gtile_action_move_up:              ""
linux_hotkeys_gtile_autotile_1:                  "1"
linux_hotkeys_gtile_autotile_10:                 "0"
linux_hotkeys_gtile_autotile_2:                  "2"
linux_hotkeys_gtile_autotile_3:                  "3"
linux_hotkeys_gtile_autotile_4:                  "4"
linux_hotkeys_gtile_autotile_5:                  "5"
linux_hotkeys_gtile_autotile_6:                  "6"
linux_hotkeys_gtile_autotile_7:                  "7"
linux_hotkeys_gtile_autotile_8:                  "8"
linux_hotkeys_gtile_autotile_9:                  "9"
linux_hotkeys_gtile_autotile_main:               m
linux_hotkeys_gtile_cancel_tiling:               esc
linux_hotkeys_gtile_change_grid_size:            ""
linux_hotkeys_gtile_move_down_vi:                j
linux_hotkeys_gtile_move_left_vi:                h
linux_hotkeys_gtile_move_right_vi:               l
linux_hotkeys_gtile_move_up_vi:                  k
linux_hotkeys_gtile_resize_down_vi:              shift+j
linux_hotkeys_gtile_resize_left_vi:              shift+h
linux_hotkeys_gtile_resize_right_vi:             shift+l
linux_hotkeys_gtile_resize_up_vi:                shift+k
linux_hotkeys_gtile_set_tiling:                  return
linux_hotkeys_gtile_show_toggle_tiling_alt:      super+return
linux_hotkeys_gtile_show_toggle_tiling:          super+enter
linux_hotkeys_gtile_snap_to_neighbors:           primary+alt+s
linux_hotkeys_gtile_resize_1:                    alt+super+1
linux_hotkeys_gtile_resize_2:                    alt+super+2
linux_hotkeys_gtile_resize_3:                    alt+super+3
linux_hotkeys_gtile_resize_4:                    alt+super+4
linux_hotkeys_gtile_resize_5:                    alt+super+5
linux_hotkeys_gtile_resize_6:                    alt+super+6
linux_hotkeys_gtile_resize_7:                    alt+super+7
linux_hotkeys_gtile_resize_8:                    alt+super+8
linux_hotkeys_gtile_resize_9:                    alt+super+9
linux_hotkeys_gtile_resize_10:                   ""
linux_hotkeys_gtile_resize_11:                   ctrl+super+1
linux_hotkeys_gtile_resize_12:                   ctrl+super+2
linux_hotkeys_gtile_resize_13:                   ctrl+super+3
linux_hotkeys_gtile_resize_14:                   ctrl+super+4
linux_hotkeys_gtile_resize_15:                   ctrl+super+5
linux_hotkeys_gtile_resize_16:                   ctrl+super+6
linux_hotkeys_gtile_resize_17:                   ctrl+super+7
linux_hotkeys_gtile_resize_18:                   ctrl+super+8
linux_hotkeys_gtile_resize_19:                   ctrl+super+9
linux_hotkeys_gtile_resize_20:                   ""
linux_hotkeys_gtile_resize_21:                   shift+super+1
linux_hotkeys_gtile_resize_22:                   shift+super+2
linux_hotkeys_gtile_resize_23:                   shift+super+3
linux_hotkeys_gtile_resize_24:                   shift+super+4
linux_hotkeys_gtile_resize_25:                   shift+super+5
linux_hotkeys_gtile_resize_26:                   shift+super+6
linux_hotkeys_gtile_resize_27:                   shift+super+7
linux_hotkeys_gtile_resize_28:                   shift+super+8
linux_hotkeys_gtile_resize_29:                   shift+super+9
linux_hotkeys_gtile_resize_30:                   ""
