---
dependencies: []

galaxy_info:
  author: theNewFlesh
  description: install jupyter extensions
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: MacOSX
    versions:
    - all
  - name: Darwin
    versions:
    - all
  galaxy_tags:
    - development
    - system
    - jupyter
    - jupyter extensions
    - ipython
    - anaconda
    - conda
