---
- name: "Debian | set dconf key value pairs"
  shell:
    cmd: "dconf write {{ item.key }} \"{{ item.value }}\""
  with_items: "{{ dconf_config_items }}"
  when: ansible_os_family == "Debian"
  tags:
    - install
    - debian