---
dependencies: []

galaxy_info:
  role_name: "gnome-tweak-tool"
  author: theNewFlesh
  description: Installs gnome-tweak-tool
  license: MIT
  min_ansible_version: 2.0.0
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - development
    - system
